
import { IntensityLevel } from "./types";

export const STUN_SERVERS = [
  { urls: "stun:stun.peerjs.com:4242" }, // PeerJS default
  { urls: "stun:stun.l.google.com:19302" },
  { urls: "stun:stun1.l.google.com:19302" },
  { urls: "stun:stun2.l.google.com:19302" },
  { urls: "stun:stun3.l.google.com:19302" },
  { urls: "stun:stun4.l.google.com:19302" },
  { urls: "stun:global.stun.twilio.com:3478" },
];

export const INTENSITY_LEVELS: { id: IntensityLevel; label: string; emoji: string; desc: string }[] = [
  { id: "friendly", label: "Friendly", emoji: "🥰", desc: "Sweet memories & funny moments" },
  { id: "romantic", label: "Romantic", emoji: "🌹", desc: "Deep connection & future dreams" },
  { id: "hot", label: "Hot", emoji: "🔥", desc: "Spicy attraction & desires" },
  { id: "very_hot", label: "Very Hot", emoji: "🌶️", desc: "Intense fantasies & passion" },
];

// New: Constants for Random Mode
export const QUESTIONS_PER_RANDOM_LEVEL = 3; // 'e' questions per player for each level
export const RANDOM_MODE_INTENSITY_ORDER: IntensityLevel[] = ["friendly", "romantic", "hot", "very_hot"];

// New: Random Emojis for Ping feature
export const RANDOM_EMOJIS = [
  '❤️', '😍', '💋', '🥰', '😘', '💖', '💞', '💕', '💌', '🌸', '✨', '😊', '😇', '🫂', '🥂', '💫', '🔥'
];

export const QUESTIONS: Record<IntensityLevel, { truth: string[]; dare: string[] }> = {
  friendly: {
    truth: [
      "What was your first impression of me?",
      "What is your favorite memory of us so far?",
      "What song always reminds you of me?",
      "What is one thing you love about my personality?",
      "If we could teleport anywhere right now, where would you take me?",
      "What is the funniest thing I’ve ever said to you?",
      "What was the sweetest message I ever sent you?",
      "What do you miss most when we’re apart?",
      "What is your favorite photo of us?",
      "How did you feel the first time we video called?",
      "What is one habit of mine that makes you smile?",
      "What’s the cutest nickname you’ve ever thought of for me?",
      "What’s something small I do that makes your day better?",
      "What is your favorite emoji to use when texting me?",
      "What made you want to talk to me every day?",
      "What is the best surprise I’ve ever given you?",
      "What is your favorite thing we’ve done on call?",
      "What’s one thing you want us to do when we finally meet?",
      "What was your favorite good morning/good night text from me?",
      "What do you think is our funniest inside joke?",
      "What is something I say that always makes you laugh?",
      "What is your favorite voice note I’ve ever sent you?",
      "What’s the silliest selfie I’ve ever sent you?",
      "What is one thing you’re excited to experience with me?",
      "What is the most thoughtful thing I’ve done for you?",
      "What do you love most about our late-night talks?",
      "What is your favorite GIF I’ve sent you?",
      "What’s something I do on camera that you find adorable?",
      "What is the best compliment I’ve ever given you?",
      "What made you realize we click so well?",
      "What is your favorite memory from our first week talking?",
      "What is the sweetest dream you’ve had about us?",
      "What do you look forward to the most when we text?",
      "What is your favorite thing about my laugh?",
      "What’s the most random thing I’ve said that stuck with you?",
      "What is one tradition you want us to start?",
      "What’s your favorite pet name I call you?",
      "What is something I do that instantly makes you happy?",
      "What is your favorite video of me?",
      "What’s the longest we’ve ever stayed on call?",
      "What is your favorite thing we have in common?",
      "What’s one thing you love about how we support each other?",
      "What is your favorite memory of us falling asleep on call?",
      "What’s something I’ve taught you?",
      "What is the cutest thing I’ve ever done on video call?",
      "What is your favorite promise we’ve made to each other?",
      "What’s one thing you always want to hear from me?",
      "What is the best care package idea you have for me?",
      "What’s your favorite “I miss you” message I’ve sent?",
      "What is your all-time favorite childhood cartoon?",
      "What hobby have you always wanted to pick up but haven’t yet?",
      "What is the best book you’ve ever read?",
      "What song always puts you in a good mood?",
      "What is your favorite way to spend a lazy weekend?",
      "What food could you eat every single day without getting tired of it?",
      "What is the funniest movie you’ve ever watched?",
      "What is one talent you wish you had?",
      "What was your favorite subject in school and why?",
      "What is your go-to comfort movie when you’re feeling down?",
      "What is the best concert or live show you’ve ever been to?",
      "What hobby do you spend the most time on these days?",
      "What is your favorite season and what do you love about it?",
      "What is one place you’ve traveled to that you’d return to in a heartbeat?",
      "What is your favorite board game or card game?",
      "What was your dream job as a kid?",
      "What is the coziest thing you own?",
      "What song do you know all the lyrics to by heart?",
      "What is your favorite type of cuisine?",
      "What is one habit you’re really proud of having?",
      "What animal do you think best represents your personality?",
      "What is your favorite holiday and why?",
      "What is the best gift you’ve ever received?",
      "What TV series could you rewatch forever?",
      "What is your favorite smell in the world?",
      "What is one thing you collect or used to collect?",
      "What is your favorite outdoor activity?",
      "What was the last funny meme that made you laugh out loud?",
      "What is your favorite dessert of all time?",
      "What superpower would you choose if you could have any?",
      "What is your favorite quote or saying?",
      "What is the best advice you’ve ever been given?",
      "What is your favorite type of weather?",
      "What was your favorite toy as a child?",
      "What is one skill you’ve learned that surprised you?",
      "What is your favorite drink on a hot day?",
      "What is the most beautiful place you’ve ever seen?",
      "What is your favorite way to relax after a long day?",
      "What band or artist have you listened to the longest?",
      "What is your favorite thing to cook or bake?",
      "What is one goal you have for the next year?",
      "What is your favorite memory from school?",
      "What is the cheesiest song you secretly love?",
      "What is your favorite piece of clothing you own?",
      "What is one thing that always makes you laugh?",
      "What is your favorite bedtime routine?",
      "What is the best road trip you’ve ever taken?",
      "What is your favorite scent of candle or perfume?",
      "What is one habit you want to start?",
      "What is your favorite memory involving family or friends?"
    ],
    dare: [
      "Send me the cutest selfie you can take right now.",
      "Sing the chorus of the first song we called ‘ours’. Send voice note.",
      "Record a 15-second video telling me why you like me.",
      "Change your phone lock screen to a photo of me for 24 hours.",
      "Send me a voice note saying my full name in the sweetest way possible.",
      "Do your best impression of me and send a video.",
      "Send me 10 heart emojis in a row, each a different color.",
      "Call me right now and say something adorable without warning.",
      "Send me a selfie making the face you make when you miss me.",
      "Record yourself saying ‘I love talking to you’ in 5 different languages.",
      "Send me a photo of something in your room that reminds you of me.",
      "Write my name on a piece of paper with a heart and send a pic.",
      "Send a voice note of you laughing for no reason.",
      "Send me your current selfie with the caption ‘Thinking of you’.",
      "Record a 10-second video blowing kisses at the camera.",
      "Send me a meme that perfectly describes how you feel about me.",
      "Call me and leave a 20-second voicemail of pure compliments.",
      "Send me a photo of you wearing my favorite color.",
      "Record yourself saying ‘You’re my favorite person’ 5 times, getting sweeter each time.",
      "Send me a screenshot of our chat that makes you smile.",
      "Make a 5-second video of you dancing happily because of me.",
      "Send me a voice note whispering something cute only I’m allowed to hear.",
      "Take a selfie with the goofiest smile possible.",
      "Send me a picture of your hand so I can ‘hold’ it.",
      "Record yourself reading a cheesy pickup line as seriously as possible.",
      "Send me a photo of the sky right now and say it reminds you of my eyes.",
      "Call me and sing ‘Happy Birthday’ even if it’s not my birthday.",
      "Send me a selfie hugging a pillow pretending it’s me.",
      "Record a video of you drawing a heart in the air with your finger.",
      "Send me a voice note saying good night in the sweetest way possible.",
      "Send me a photo of something you’re eating and say it’s not as sweet as me.",
      "Make a short video waving at the camera saying you miss me.",
      "Send me a selfie with a handwritten note that says my name.",
      "Record yourself counting from 1 to 10 while saying one thing you like about me each number.",
      "Send me a picture of your pet (or a stuffed animal) and say it misses me too.",
      "Call me and make random cute noises for 15 seconds.",
      "Send me a voice note telling me your favorite thing about today because we talked.",
      "Take a selfie doing your best heart fingers.",
      "Send me a photo of your screen with our chat open.",
      "Record yourself saying ‘I’m lucky to have you’ in the mirror.",
      "Send me a video of you pretending to fall asleep smiling because of me.",
      "Send me a picture of the moon/sun and say it’s shining for us.",
      "Record a 10-second dramatic reading of our last 3 messages.",
      "Send me a selfie wearing something I’ve complimented before.",
      "Call me and say ‘I love you’ in the cutest voice you can make.",
      "Send me a voice note humming our favorite song.",
      "Take a photo holding up a sign that says ‘Mine ❤️’. (paper/phone note)",
      "Send me a video doing a little happy dance for 10 seconds.",
      "Record yourself saying my name 10 times, each time sweeter than the last.",
      "Send me a selfie with the biggest genuine smile you can do right now.",
      "Tell me your favorite childhood memory in detail.",
      "Describe your ideal perfect day from morning to night.",
      "Share the story behind your favorite photo on your phone.",
      "Tell me about the nicest thing anyone has ever done for you.",
      "Recite the lyrics of your current favorite song.",
      "Describe your dream house in as much detail as you can.",
      "Tell me about a time you laughed so hard you cried.",
      "Share one thing on your bucket list and why it’s there.",
      "Describe the best meal you’ve ever had.",
      "Tell me your favorite joke (even if it’s corny).",
      "Share a happy memory from your last birthday.",
      "Describe what your perfect weekend looks like.",
      "Tell me about a book or movie that changed your perspective.",
      "Share your favorite family tradition.",
      "Describe the coziest evening you can imagine.",
      "Tell me about the kindest stranger you’ve ever met.",
      "Share one thing you’re really grateful for today.",
      "Describe your favorite holiday memory.",
      "Tell me about a hobby you loved as a kid.",
      "Share the song that always makes you dance.",
      "Describe your favorite place you’ve ever visited.",
      "Tell me about a goal you’ve already achieved that you’re proud of.",
      "Share your go-to feel-good movie and why you love it.",
      "Describe the best surprise you’ve ever had.",
      "Tell me your favorite bedtime story or fairy tale.",
      "Share one habit that makes you feel productive.",
      "Describe your favorite season in detail.",
      "Tell me about the funniest dream you remember.",
      "Share your favorite quote and what it means to you.",
      "Describe the perfect gift you’d love to receive.",
      "Tell me about a teacher or mentor who inspired you.",
      "Share your favorite way to celebrate small wins.",
      "Describe your dream vacation destination.",
      "Tell me about the last time you felt really proud of yourself.",
      "Share a song that reminds you of your childhood.",
      "Describe your favorite comfort food in detail.",
      "Tell me one thing you love about your daily routine.",
      "Share your favorite animal and why you relate to it.",
      "Describe the best concert memory you have.",
      "Tell me about a friend who always makes you smile.",
      "Share your favorite relaxing activity.",
      "Describe your ideal morning routine.",
      "Tell me about the book you couldn’t put down.",
      "Share one small thing that always brightens your day.",
      "Describe your favorite scent memory.",
      "Tell me about a time you felt completely at peace.",
      "Share your favorite motivational saying.",
      "Describe the best dessert you’ve ever tasted.",
      "Tell me about a hobby you want to restart.",
      "Share your favorite memory with a pet (or dream pet)."
    ]
  },

  romantic: {
    truth: [
      "When did you realize you were falling for me?",
      "What is your biggest dream for our future together?",
      "What do you love most about the way we love each other?",
      "How do you feel when we’re on call for hours?",
      "What is one thing I do that makes your heart melt?",
      "What do you imagine our first hug will feel like?",
      "What is the most romantic thing you want to do when we meet?",
      "What part of my voice makes you feel safe?",
      "What is a future trip you want to plan with me?",
      "What do you think our couple nickname should be?",
      "What is one promise you want to make to me right now?",
      "What is the sweetest dream you’ve had about us?",
      "How do you want me to wake you up when we live together?",
      "What is something you want to experience with me for the first time?",
      "What do you love most about falling asleep on call together?",
      "What is one tradition you want us to have as a couple?",
      "What do you think I love most about you?",
      "What is a love song that perfectly describes us?",
      "What is the most romantic message I’ve ever sent you?",
      "Where do you want to have our first kiss?",
      "What is one thing you never want to change about us?",
      "What do you want our first ‘I love you’ in person to be like?",
      "What is something small you want to do every day when we’re together?",
      "What is your favorite late-night conversation we’ve had?",
      "What do you imagine our home will look like one day?",
      "What is one thing you want to write on a letter to me?",
      "What is your favorite way I say ‘I love you’?",
      "What moment made you think ‘This is real’?",
      "What is a pet name you want to call me forever?",
      "What is one thing you want engraved on something we share?",
      "What do you want our first dance song to be?",
      "What is the most romantic surprise you want from me?",
      "What is something you want to say to me on our wedding day (if we get there)?",
      "What is your favorite thing about the way we support each other?",
      "What is one fear you had about long distance that I erased?",
      "What is the most beautiful thing I’ve ever said to you?",
      "What do you want our kids/pets to be named (just for fun)?",
      "What is one thing you want us to do every anniversary?",
      "What is your favorite memory of us saying good night?",
      "What is something you want to thank me for?",
      "What is one thing you want to experience at least once with me?",
      "What is the most romantic place you want to watch the sunset with me?",
      "What is one habit of mine you want to keep forever?",
      "What is a love letter line you want to write to me?",
      "What is your favorite photo you have of me and why?",
      "What is one thing you want to tell me when we’re old and gray?",
      "What is your favorite ‘I miss you’ we’ve ever said?",
      "What is one thing you never get tired of hearing from me?",
      "What is the most romantic dare you’ve ever done for me?",
      "What is one reason long distance is worth it for us?",
      "What is the most romantic movie you’ve ever watched?",
      "What love song do you think describes how you feel about me?",
      "What is your favorite way to show someone you love them?",
      "What was your first crush like?",
      "What is your idea of the perfect romantic gesture?",
      "What love story (book/movie/real) inspires you the most?",
      "What is your favorite thing about being in love?",
      "What memory from your past relationships are you most grateful for?",
      "What is one thing you learned about love before meeting me?",
      "What is your favorite couple activity you’ve seen or heard about?",
      "What love language do you feel the most?",
      "What is the sweetest date you’ve ever been on (before me)?",
      "What is your favorite romantic quote?",
      "What do you think is the key to a long-lasting relationship?",
      "What is one thing you always wanted in a partner that I have?",
      "What is your favorite slow dance song?",
      "What was your parents’ or friends’ relationship that you admire?",
      "What is the most romantic place you’ve ever been?",
      "What is one tradition you had or want in past relationships?",
      "What love song makes you think of our future?",
      "What is your favorite way to receive affection?",
      "What is the best relationship advice you’ve ever received?",
      "What is one thing you believe about soulmates?",
      "What is your favorite memory of feeling butterflies?",
      "What is the most romantic book you’ve read?",
      "What is one habit of happily married couples you admire?",
      "What is your favorite pet name you’ve ever been called?",
      "What is the longest relationship you’ve been in and what did you learn?",
      "What is one romantic thing you’ve always wanted to experience?",
      "What is your favorite wedding song or scene from a movie?",
      "What is the most important value in a relationship for you?",
      "What is one way past partners made you feel special?",
      "What is your favorite type of date night?",
      "What is the sweetest thing someone has ever said to you?",
      "What is one dream you have for a future relationship?",
      "What is your favorite romantic comedy?",
      "What is one lesson about love you wish you knew earlier?",
      "What is the most beautiful love letter or message you’ve received?",
      "What is your favorite way to celebrate anniversaries?",
      "What is one thing you think makes our connection unique?",
      "What is your favorite memory of falling in love?",
      "What is the most romantic season for you and why?",
      "What is one quality you always looked for in a partner?",
      "What is your favorite love poem or lyric?",
      "What is the best surprise date idea you’ve heard of?",
      "What is one thing you love about how we communicate?",
      "What is your favorite memory involving a past crush?",
      "What is one romantic movie scene you want to recreate?",
      "What is the sweetest dream you’ve had about love?",
      "What is your favorite way to end a perfect date?"
    ],
    dare: [
      "Call me right now and tell me you love me without saying the words.",
      "Write a short love letter (3-5 sentences) and send it.",
      "Send a voice note describing our perfect future date in detail.",
      "Record a video of you slow dancing alone while thinking of me.",
      "Send me a playlist of 5 songs that remind you of me with explanations.",
      "Call me and read me a love quote as if you wrote it.",
      "Send a selfie with a handwritten note saying why you love me.",
      "Record yourself saying ‘I can’t wait to marry you one day’ (even if joking).",
      "Send a 30-second voice note of everything you want to do when we meet.",
      "Call me and describe holding my hand in detail for 1 minute.",
      "Send me a photo of something you’d buy me right now if you could.",
      "Record yourself whispering ‘You’re my home’ 5 times.",
      "Send me a video of you drawing our future house (even badly).",
      "Call me and say my name like you’ll say it on our wedding day.",
      "Send a voice note promising me one thing for our future.",
      "Take a selfie looking at me like I’m the only person in the world.",
      "Record a video of you kissing the camera slowly.",
      "Send me a picture of the ring style you’d want me to have one day.",
      "Call me and tell me what you’d say if you proposed right now.",
      "Send a 20-second voice note describing how my voice makes you feel.",
      "Record yourself singing a love song dedicated to me (even badly).",
      "Send me a photo of the sky and say ‘This is how big my love is’.",
      "Call me and describe our first morning waking up together.",
      "Send a voice note saying good night as if we’re in the same bed.",
      "Record yourself writing my name in the air with your finger on video.",
      "Send me a selfie with tears (fake or real) saying you miss me so much.",
      "Call me and tell me one reason you’re proud to be mine.",
      "Send a picture of something you want us to wear as a couple.",
      "Record yourself reading your favorite romantic message I sent you.",
      "Send a voice note describing the moment you want to say ‘I love you’ in person.",
      "Call me and pretend we’re on our honeymoon for 1 minute.",
      "Send me a photo of a place you want to kiss me one day.",
      "Record a video of you hugging yourself pretending it’s me.",
      "Send a 15-second voice note saying what you love most about us.",
      "Call me and describe in detail how you’ll hug me at the airport.",
      "Send me a selfie with a rose filter or real flower.",
      "Record yourself saying ‘Forever with you isn’t long enough’ dramatically.",
      "Send a voice note listing 5 things you want to do on our first week together.",
      "Call me and speak only in love quotes for 30 seconds.",
      "Send me a photo of your hand with a ring drawn on it.",
      "Record a video of you looking at the moon saying it’s not as beautiful as me.",
      "Send a voice note describing the scent you want me to wear.",
      "Call me and tell me what our kids would look like (for fun).",
      "Send a picture of a place you want to call ‘our spot’ one day.",
      "Record yourself saying ‘You’re my soulmate’ in 5 languages.",
      "Send a voice note of you planning our dream wedding in 1 minute.",
      "Call me and describe the first time you want to cry in my arms.",
      "Send a selfie with the caption ‘Waiting for you forever’. (post or send privately)",
      "Record yourself promising me the world on video.",
      "Send a voice note saying ‘I choose you every day’ softly.",
      "Tell me in detail what your dream proposal would look like.",
      "Describe the perfect romantic evening you’d plan for me.",
      "Share the most romantic thing you’ve ever wanted to say to someone.",
      "Tell me your favorite memory of feeling truly loved.",
      "Describe how you imagine our 10-year anniversary.",
      "Share one thing you’ve always wanted to hear from a partner.",
      "Tell me the story of your favorite romantic dream.",
      "Describe the qualities of your ideal future with someone.",
      "Share your favorite love song and why it’s special.",
      "Tell me what you think our wedding dance song should be.",
      "Describe the most romantic trip you’d want to take with a partner.",
      "Share one lesson about love you’re glad you learned.",
      "Tell me your idea of the perfect Valentine’s Day.",
      "Describe how you picture us growing old together.",
      "Share the sweetest compliment you’ve ever received.",
      "Tell me about a couple you admire and why.",
      "Describe your favorite romantic scene from any movie.",
      "Share one thing you want in every future anniversary.",
      "Tell me the most romantic gesture you’ve ever done for someone.",
      "Describe what forever means to you in a relationship.",
      "Share your favorite way to say ‘I love you’ without words.",
      "Tell me about the best date you’ve ever planned in your mind.",
      "Describe the feeling of butterflies in detail.",
      "Share one romantic tradition you want to start with someone.",
      "Tell me your favorite love quote and who it’s from.",
      "Describe the perfect morning waking up next to someone you love.",
      "Share what you think is the most romantic city in the world.",
      "Tell me one thing you believe true love feels like.",
      "Describe your ideal cozy winter date.",
      "Share the most heartfelt message you’ve ever written.",
      "Tell me about a time someone made you feel truly cherished.",
      "Describe our future home in romantic detail.",
      "Share your favorite slow song for cuddling.",
      "Tell me what marriage means to you.",
      "Describe the perfect summer evening with a partner.",
      "Share one romantic wish you have for us.",
      "Tell me the sweetest thing you’ve felt about someone.",
      "Describe your favorite way to celebrate love daily.",
      "Share a romantic memory that still makes you smile.",
      "Tell me what you think our love story title would be.",
      "Describe the most romantic sunset date imaginable.",
      "Share one thing you learned about yourself through love.",
      "Tell me your favorite romantic book couple.",
      "Describe how you want to be loved long-term.",
      "Share the most beautiful love lyric you know.",
      "Tell me about the best goodnight you’ve ever had.",
      "Describe your dream honeymoon destination.",
      "Share one way you show love that feels natural to you.",
      "Tell me what you admire most in lasting couples.",
      "Describe the perfect rainy day spent with someone special."
    ]
  },

  hot: {
    truth: [
      "What was the first physical thing you noticed about me?",
      "What part of my body do you think about the most?",
      "What’s the sexiest photo I’ve ever sent you?",
      "What turns you on the most when we talk dirty?",
      "Where is your favorite place on your body to be kissed?",
      "What outfit of mine do you want to rip off the most?",
      "What is your biggest turn-on that I do without realizing?",
      "What’s something you want to try in bed with me?",
      "What is the hottest voice note I’ve ever sent you?",
      "What do you imagine I sound like when I moan?",
      "What’s a body part of mine you want to leave marks on?",
      "What is your favorite kind of kiss?",
      "What’s the most teasing thing I’ve ever said to you?",
      "What turns you on instantly when you see my name pop up?",
      "What’s one thing you want me to wear just for you?",
      "What is the sexiest dream you’ve had about me?",
      "What’s a word I say that instantly makes me horny?",
      "What is your favorite way to be teased?",
      "What’s the hottest thing you want to whisper in my ear?",
      "What part of foreplay do you want the most from me?",
      "What is one fantasy location you want to have sex with me?",
      "What’s the naughtiest thought you’ve had on call with me?",
      "What do you want me to call you in bed?",
      "What’s something you want to do to me in front of a mirror?",
      "What is your favorite pace – slow and sensual or fast and rough?",
      "What’s the sexiest thing I’ve worn on video call?",
      "What is one toy you’d want us to use together?",
      "What’s the longest you’ve edged thinking about me?",
      "What is a roleplay scenario that turns you on?",
      "What’s the hottest compliment I’ve ever given your body?",
      "What is one thing you want to do to me after a long time apart?",
      "What’s your favorite type of lingerie on me?",
      "What is the most sensitive spot on your body right now?",
      "What’s something you want me to moan in your ear?",
      "What is a dirty promise you want to make me?",
      "What’s the sexiest thing we’ve ever done on call?",
      "What is one position you can’t wait to try with me?",
      "What’s the hottest thing you’d do if I was there for only 10 minutes?",
      "What is your favorite way to be dominated/taken control of?",
      "What’s something you want me to beg for?",
      "What is the dirtiest text I’ve ever sent you?",
      "What’s one thing that always makes you hard/wet thinking about me?",
      "What is a risky place you’d want to fool around with me?",
      "What’s the sexiest voice you want me to use on call?",
      "What is one thing you want to watch me do to myself?",
      "What’s your biggest kink you haven’t told me yet?",
      "What is the hottest thing you want to record for me?",
      "What’s one thing you want me to spank?",
      "What is your favorite after-sex thing to do with me?",
      "Rate how turned on you are right now thinking about me (1-10).",
      "What are you wearing right now (in full detail)?",
      "What is the sexiest piece of clothing you own?",
      "What color underwear are you wearing today?",
      "What is one outfit you wore in the past that you felt hottest in?",
      "What part of your body do you like showing off the most?",
      "What is your favorite type of underwear to wear?",
      "What is the most daring thing you’ve ever worn in public?",
      "What fabric feels the sexiest against your skin?",
      "What is one compliment about your body you love hearing?",
      "What is your favorite way to feel desired?",
      "What scent do you wear that you think is the sexiest?",
      "What is one physical feature you’re most confident about?",
      "What is the hottest thing someone has ever said about your appearance?",
      "What is your favorite style of dress or outfit on a date?",
      "What is one desire you have when you’re alone at night?",
      "What is the sexiest dream you remember having (non-specific)?",
      "What turns you on the most about confidence in a partner?",
      "What is one thing you love about your body in the mirror?",
      "What is your favorite way to tease someone you like?",
      "What is the most flattering lighting for your body?",
      "What is one fantasy you’ve had about being desired?",
      "What is your favorite part of foreplay in your imagination?",
      "What is the sexiest song you know?",
      "What is one habit you have when you feel attracted to someone?",
      "What is the hottest memory you have of feeling wanted?",
      "What is your favorite temperature for intimate moments?",
      "What is one thing you wish partners noticed more about you physically?",
      "What is the most sensual food you’ve ever eaten?",
      "What is your favorite way to be touched (non-explicit)?",
      "What is one desire you feel when listening to certain music?",
      "What is the sexiest movie scene you remember?",
      "What is your favorite lingerie or loungewear brand?",
      "What is one thing that instantly boosts your confidence sexually?",
      "What is the hottest outfit you’ve seen on someone else?",
      "What is your favorite way to flirt over text?",
      "What is one physical sensation you crave the most?",
      "What is the sexiest thing about your voice?",
      "What is one desire you have about slow, teasing touches?",
      "What is your favorite candle scent for a romantic night?",
      "What is the most attractive quality in a partner’s body for you?",
      "What is one thing you love wearing to bed?",
      "What is your favorite way to feel sexy alone?",
      "What is the hottest compliment you’ve ever given someone?",
      "What is one desire you have about being kissed in the rain?",
      "What is your favorite style of kiss in your fantasies?",
      "What is the sexiest dance move you know or want to learn?",
      "What is one thing that makes you feel irresistible?",
      "What is your favorite erotic book or story (if any)?",
      "What is the most sensual memory involving touch from the past?",
      "What is one desire you feel when you’re really relaxed?"
    ],
    dare: [
      "Send a voice note moaning my name softly.",
      "Describe in detail what you’re wearing under your clothes right now (voice note).",
      "Send a close-up photo of your favorite body part to kiss.",
      "Send a 20-second voice note of dirty talk about what you want right now.",
      "Take a shirtless/thigh/chest photo (your choice) and send it.",
      "Send a voice note describing exactly how you’d kiss my neck.",
      "Unbutton/lower one piece of clothing and send proof.",
      "Send a photo biting your lip looking at the camera.",
      "Record yourself saying what you want me to do to you tomorrow night.",
      "Send a voice note breathing heavily for 15 seconds while saying my name.",
      "Take a photo in your sexiest underwear (or imply it).",
      "Send a 30-second voice note describing a quickie with me.",
      "Touch yourself over clothes for 20 seconds and send a voice note reaction.",
      "Send a photo of your hand down your pants (no explicit nudity).",
      "Record yourself saying ‘I’m yours’ in your deepest/sexiest voice.",
      "Send a voice note counting down from 10 while imagining me on top of you.",
      "Take a mirror selfie in just a towel or less (tease only).",
      "Send a photo of the body part you want me to kiss first.",
      "Record a 15-second teasing strip (remove one layer only).",
      "Send a voice note describing your favorite position with me in detail.",
      "Call me and whisper something so dirty I’ll blush.",
      "Send a close-up of your lips with the caption ‘These want you’.",
      "Record yourself touching your neck/chest while thinking of me.",
      "Send a photo with your shirt lifted just enough to tease.",
      "Voice note: Tell me exactly where your hands would be on me right now.",
      "Send a picture of you in bed with the caption ‘Wish you were here’. No face needed.",
      "Record yourself saying ‘I need you’ getting progressively breathier.",
      "Send a voice note describing how you’d undress me slowly.",
      "Take a photo from a low angle that drives me crazy.",
      "Send a 20-second voice note of you edging and saying my name.",
      "Record yourself lightly spanking yourself and reacting.",
      "Send a photo of your collarbone with a bite mark (fake is fine).",
      "Voice note: Describe what you’d do if I sent you nudes right now.",
      "Send a mirror photo with messy hair and flirty eyes.",
      "Record yourself saying 5 dirty things you want me to do to you.",
      "Send a close-up of your thighs with hand placement tease.",
      "Voice note: Pretend we’re on the phone having phone sex for 30 seconds.",
      "Send a photo wearing something I’ve said turns me on.",
      "Record yourself tracing your lips with your finger while staring at camera.",
      "Send a voice note begging me to come over (as if I could).",
      "Take a shirtless selfie with hickeys drawn on (fake is fine).",
      "Send a 15-second video of you moving your hips slowly.",
      "Voice note: Rate my body 1-10 and explain why it’s a 10.",
      "Send a photo of your hand gripping the sheets.",
      "Record yourself saying ‘Use me’ in the hottest way possible.",
      "Send a close-up of your neck with the caption ‘Waiting for your lips’.",
      "Voice note: Describe the sound you’d make when I first enter you.",
      "Send a teasing photo with one less layer than before.",
      "Record yourself growling my name possessively.",
      "Send a voice note saying ‘I’m touching myself thinking of you’ (even if lying).",
      "Describe in detail what you’re wearing right now, layer by layer.",
      "Tell me the sexiest outfit you’ve ever worn and why it felt hot.",
      "Describe your favorite underwear you own in detail.",
      "Share one desire you’re feeling right now in a teasing way.",
      "Tell me what you sleep in most nights.",
      "Describe how you feel when you wear something that makes you feel sexy.",
      "Share the color and style of your current underwear.",
      "Tell me one thing you love about your body out loud.",
      "Describe the sexiest dream you’ve had recently (keep it tasteful).",
      "Tell me what scent you’re wearing today and why you chose it.",
      "Share one physical feature you’re proud of and why.",
      "Describe your ideal sexy date night outfit for yourself.",
      "Tell me one thing that makes you feel desired instantly.",
      "Share the hottest song on your playlist right now.",
      "Describe how you like to be looked at when someone desires you.",
      "Tell me one fantasy you have about slow dancing.",
      "Share what fabric feels best on your skin and why.",
      "Describe the most confident you’ve ever felt physically.",
      "Tell me one teasing thing you’d wear just to drive someone crazy.",
      "Share your favorite way to set a romantic mood with lighting.",
      "Describe one sensation you crave when thinking intimately.",
      "Tell me the sexiest movie kiss you remember.",
      "Share one compliment you secretly love getting about your looks.",
      "Describe your favorite loungewear that feels luxurious.",
      "Tell me one thing you do when you want to feel attractive.",
      "Share the hottest lyric you know from any song.",
      "Describe how confidence makes someone more attractive to you.",
      "Tell me one desire you have about soft, lingering touches.",
      "Share your favorite perfume or cologne note.",
      "Describe the sexiest lighting you can imagine for intimacy.",
      "Tell me one thing you’d wear on a fantasy date night.",
      "Share a teasing habit you have when you like someone.",
      "Describe how music can change your mood to sensual.",
      "Tell me one physical compliment you’d love to hear more.",
      "Share the most flattering outfit you’ve ever owned.",
      "Describe one way you like to flirt in person.",
      "Tell me your favorite temperature for cuddling intimately.",
      "Share one desire you feel when wearing something silky.",
      "Describe the sexiest voice tone you find attractive.",
      "Tell me one thing that makes you blush when complimented.",
      "Share your favorite sensual food experience.",
      "Describe how you imagine the perfect teasing kiss.",
      "Tell me one outfit detail that always makes you feel powerful.",
      "Share the hottest non-explicit scene from a book or show.",
      "Describe one way you pamper yourself to feel sexy.",
      "Tell me your favorite candle or room scent for romance.",
      "Share one desire about being desired from across the room.",
      "Describe the most attractive smile you can imagine.",
      "Tell me one thing you love seeing on a partner’s body.",
      "Share your favorite way to relax into intimate thoughts."
    ]
  },

  very_hot: {
    truth: [
      "What is the filthiest fantasy you have about me?",
      "Have you ever masturbated while on call with me?",
      "What is your ultimate sexual kink you want to try with me?",
      "What is the dirtiest thing you’ve ever done thinking of me?",
      "What is your favorite porn category that reminds you of us?",
      "What is one taboo thing you’d do with me if no one ever knew?",
      "How many times a day do you think about fucking me?",
      "What is the roughest you want me to be with you?",
      "What is a degrading/pet name you want me to call you in bed?",
      "What is the most public place you’d have sex with me?",
      "Would you let me record us having sex?",
      "What is your favorite way to be punished?",
      "Have you ever sent nudes while thinking of me specifically?",
      "What is one hole you want me to pay the most attention to?",
      "What is the longest you’ve gone without cumming because of me?",
      "What is a threesome fantasy you have (even if you don’t want it IRL)?",
      "What is the sluttiest outfit you’d wear just for me?",
      "What is one sex toy you own that you use thinking of me?",
      "What is your favorite type of orgasm to have/give?",
      "What is the dirtiest thing you want me to say while inside you?",
      "Would you ever let me use you whenever I wanted for a day?",
      "What is your biggest cum fantasy involving me?",
      "What is one thing you’d never do with anyone else but me?",
      "How loud do you think you’d be with me?",
      "What is your safe word (or do you want one)?",
      "What is the most degrading thing that turns you on?",
      "Have you ever tasted yourself thinking of me?",
      "What is a roleplay where I have complete power over you?",
      "What is the most times you’ve cum in one session thinking of me?",
      "What is one bodily fluid kink you have?",
      "Would you film yourself for me right now if I asked?",
      "What is the roughest choke you want from me?",
      "What is your favorite position to be completely dominated in?",
      "What is one thing you want tied/restrained during sex?",
      "What is the dirtiest dare you’ve ever done for me?",
      "Would you let me share you (hypothetically)?",
      "What is your pain tolerance in bed?",
      "What is one sex act you’re nervous but curious to try with me?",
      "What is the fastest you’ve ever cum thinking of me?",
      "What is your favorite way to be woken up sexually?",
      "What is one word that would make you cum instantly if I said it?",
      "What is the nastiest text you’ve ever wanted to send me?",
      "Would you ever do mutual masturbation on video call?",
      "What is your biggest ‘free use’ fantasy?",
      "What is one thing you want written on your body during sex?",
      "What is the most possessive thing you want me to do to you?",
      "What is your favorite creampie/ facial / swallowing fantasy?",
      "What is the longest sex session you want with me?",
      "What is one outfit that would make you drop to your knees?",
      "What is the dirtiest thing you want to do on our first night together?",
      "What is the naughtiest thought you’ve had this week?",
      "What is one sexual fantasy you’ve never shared with anyone?",
      "What is your favorite type of touch that drives you wild?",
      "What is the most intense desire you’ve felt recently?",
      "What is one position you think about the most?",
      "What is your favorite way to be teased until you can’t take it?",
      "What is the hottest thing your body craves right now?",
      "What is one kink you’ve always been curious about?",
      "What is your favorite sound to hear during intimacy?",
      "What is the most sensitive part of your body besides the obvious?"
    ],
    dare: [
      "Send a full nude (or as close as you’re comfortable) right now.",
      "Masturbate for 1 minute on video call or send timed proof.",
      "Send a video of you playing with yourself (no face if shy).",
      "Record a 30-second video moaning my name while touching yourself.",
      "Send a video of you using a toy and saying my name.",
      "Call me and have phone sex for at least 2 minutes.",
      "Send a video cumming (or faking intensely) while saying my name.",
      "Record yourself spanking yourself 10 times hard, counting out loud.",
      "Send a close-up video of you fingering yourself / stroking.",
      "Edge yourself 3 times and send voice notes of each near-orgasm.",
      "Send a video of you deepthroating something (finger/banana/toy).",
      "Record yourself begging to cum but not allowing yourself for 30 seconds.",
      "Send a video of you in doggy position begging for me.",
      "Call me and let me control your vibrator/toy for 2 minutes (or pretend).",
      "Send a video of you tasting yourself off your fingers.",
      "Record yourself saying the filthiest things you want me to do to you.",
      "Send a video of you humping a pillow moaning my name.",
      "Record yourself choking yourself lightly while touching.",
      "Send a video of you spreading and teasing for the camera.",
      "Call me and cum on the call (or fake convincingly).",
      "Send a video of you slapping your most sensitive parts.",
      "Record yourself writing my name on your body with something.",
      "Send a video of you using ice on your nipples/genitals.",
      "Record yourself saying ‘I’m lucky to have you’ in the little slut’ while touching.",
      "Send a video of you in the shower teasing (no explicit if not comfy).",
      "Call me and describe your orgasm as it happens (real or acted).",
      "Send a video of you crawling toward the camera begging.",
      "Record yourself overstimming after cumming (or pretending).",
      "Send a video of you gagging on your fingers saying my name.",
      "Record yourself calling me Daddy/Mommy/Master and begging.",
      "Send a full nude (or as close as you’re comfortable) right now."
    ]
  },
};
